<form id="loginForm" action="" method="post">
    <table>
        <tr>
            <td><?php echo __('User name:'); ?></td>
            <td><input type="text" name="loginUsername" value="<?php echo ''; ?>" /></td>
        </tr>
        <tr>
            <td><?php echo __('Password:'); ?></td>
            <td><input type="password" name="loginPassword" value="<?php echo ''; ?>" /></td>
        </tr>
        <tr>
            <td colspan="2"><input type="submit" value="<?php echo __('Accept'); ?>" /></td>
        </tr>
    </table>
</form>